services:
  db:
    image: postgres:14.1-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tms

# While running the application locally change the server.port in application.yml from 8081 to any other available port to avoid port conflict
# and comment the below service config

  taxi-management-service:
    image: taxi-management-service
    build: .
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tms
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
